services:
  mood2anime:
    build:
      dockerfile: ./Dockerfile
      context: .
    restart: always
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/