# Generated by Django 5.1.5 on 2025-04-05 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('trailer', models.URLField()),
                ('releaseYear', models.DateField()),
                ('review', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=375)),
                ('portraitImage', models.ImageField(upload_to='anime/portraitImage/')),
            ],
        ),
        migrations.CreateModel(
            name='genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='studios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='studios/picture/')),
            ],
        ),
        migrations.CreateModel(
            name='genreAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.anime')),
                ('genreID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genres')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='studio',
            field=models.ManyToManyField(to='main.studios'),
        ),
    ]
