# Generated by Django 3.2.19 on 2024-05-10 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('trailer', models.URLField()),
                ('releaseYear', models.DateField()),
                ('review', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=375)),
            ],
        ),
        migrations.CreateModel(
            name='genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='img/genresImg/')),
            ],
        ),
        migrations.CreateModel(
            name='moodAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.anime')),
                ('moodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mood')),
            ],
        ),
        migrations.CreateModel(
            name='genreAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.anime')),
                ('genreID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genres')),
            ],
        ),
    ]
